<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="<?=ASSETS_URL;?>/images/logo.png" />
    
    <title><?= $titre ?></title>
    
    <link href="<?=ASSETS_URL;?>/css/all-styles.min.css" rel="stylesheet" />
    <script src="<?=ASSETS_URL;?>/js/all-scripts.min.js"></script>

    <link href="<?=ASSETS_URL;?>/fonts/fonts.css" rel="stylesheet" />
    <link href="<?=ASSETS_URL;?>/fonts/font-awesome.css" rel="stylesheet" />
</head>
